name: scan with acunetix
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Acuneitx Scan
        run: |
          curl -k -i --request POST --url "https://siiuftykod9b.share.zrok.io/api/v1/scans" --header "X-Auth: 1986ad8c0a5b3df4d7028d5f3c06e936c4f71041747b142f6a2fb72cb8375f013" --header "content-type: application/json" --data '{"profile_id":"11111111-1111-1111-1111-111111111111", "schedule":{"disable":false,"start_date":null,"time_sensitive":false}, "user_authorized_to_scan":"yes", "target_id":"3cd8e3c6-a586-4869-bd44-4344cd26cf73", "login":{"kind":"automatic", "credentials":{"enabled":true, "username":"jim@juice-sh.op", "password":"ncc-1701", "url":"https://w7dre95g4hem.share.zrok.io/#/login"}}}'
