name: SAST scan autheticated with semgrep docker
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  semgrep-full:
      runs-on: ubuntu-latest
      container:
        image: returntocorp/semgrep

      steps:

        # step 1
        - name: clone application source code
          uses: actions/checkout@v4

        # step 2
        - name: full scan
          run: |
            semgrep \
              --sarif --output semgrep_docker_report.sarif \
              --metrics=off \
              --config="p/default"

        # step 3
        
        - name: save report as pipeline artifact
          uses: actions/upload-artifact@v4
          with:
            name: semgrep_docker_report.sarif
            path: semgrep_docker_report.sarif
            
        # step 4
        - name: Download report
          uses: actions/download-artifact@v4
          with: 
            name: semgrep_docker_report.sarif
