name: scan autheticated with zap v2
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
    compile:
        name: Run my site
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v4
          - name: Run the build process with Docker
            uses: addnab/docker-run-action@v3
            with:
                image: dcmjid/my-php-app:php-app-1.0
                options: -p 8080:80
                run: |
                    - containerip=$(docker inspect -f "{{ .NetworkSettings.Networks.bridge.IPAddress }}" my-app)
                    - echo $containerip  # Get container IP so we can test it
                    - curl -k -i https://$containerip:3000  # test connecion to site
